spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curso_spring_boot?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: admin123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
